# Generated by Django 3.0.3 on 2020-02-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_data',
            fields=[
                ('Query_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=30, verbose_name='Name')),
                ('father_name', models.CharField(max_length=30, verbose_name='Father')),
                ('Address', models.CharField(max_length=30)),
                ('Test_performed', models.BooleanField()),
                ('test_teacher', models.CharField(max_length=30)),
                ('date_of_test', models.DateField()),
                ('Contact', models.CharField(max_length=20)),
                ('Addmission_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required', to='dependencies.Class')),
                ('Fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Fee_Category')),
                ('Previous_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.School')),
                ('Suggested_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested', to='dependencies.Class')),
                ('last', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class')),
            ],
        ),
    ]
