# Generated by Django 3.0.3 on 2020-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_data',
            fields=[
                ('Query_code', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, verbose_name='Name')),
                ('father_name', models.CharField(default=1, max_length=30, verbose_name='father')),
                ('Address', models.CharField(default=1, max_length=30)),
                ('Test_performed', models.BooleanField(default=1)),
                ('suggested_class', models.CharField(default=1, max_length=20)),
                ('test_teacher', models.CharField(default=1, max_length=30)),
                ('date_of_test', models.DateTimeField(auto_now_add=True)),
                ('Contact', models.CharField(default=1, max_length=20)),
            ],
        ),
    ]
