# Generated by Django 3.0.3 on 2020-03-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_information', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('fee_type_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('fee_type', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StFeeDefine',
            fields=[
                ('fee_def_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('concession_percent', models.IntegerField()),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.ClassFee')),
                ('gr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr')),
            ],
        ),
        migrations.CreateModel(
            name='FeeRegister',
            fields=[
                ('fee_reg_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('fee_amount', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=2)),
                ('due_date', models.DateField()),
                ('paid_amount', models.CharField(blank=True, max_length=5)),
                ('fee_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.ClassFee')),
                ('gr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr')),
            ],
        ),
    ]
