# Generated by Django 3.0.3 on 2020-03-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeregister',
            old_name='fee_type_id',
            new_name='fee_reg_id',
        ),
    ]
