# Generated by Django 3.0.3 on 2020-02-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('surname', models.CharField(max_length=200, unique=True)),
                ('father_name', models.CharField(max_length=200)),
                ('ph_no_father', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('ph_no_mother', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fee_Category',
            fields=[
                ('fee_category_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('fee_category_name', models.CharField(max_length=100)),
                ('percent', models.FloatField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(max_length=200)),
                ('school_area', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sect_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('sect_name', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
