# Generated by Django 3.0 on 2020-02-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_work',
            fields=[
                ('homework_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('sections', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=30)),
                ('subjects', models.CharField(max_length=20)),
                ('chapter', models.CharField(max_length=50)),
                ('page', models.IntegerField(max_length=30)),
                ('descriptions', models.CharField(max_length=300)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_class', to='dependencies.Class')),
            ],
        ),
    ]
