# Generated by Django 3.0.3 on 2020-03-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_information', '0001_initial'),
        ('dependencies', '0002_auto_20200309_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('assesment_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('assesment_name', models.CharField(max_length=30, verbose_name='Quater')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('semester_name', models.CharField(max_length=30, verbose_name='semester')),
                ('exam_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Semesterbreakup',
            fields=[
                ('semesterbreakup_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('semesterbreakup_name', models.CharField(max_length=30, verbose_name='semester-breakup')),
                ('exam_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam')),
                ('semester_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Quater',
            fields=[
                ('quater_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('quater_name', models.CharField(max_length=30, verbose_name='Quater')),
                ('exam_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam')),
                ('semester_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semester')),
                ('semesterbreakup_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semesterbreakup')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('total_marks', models.CharField(max_length=30, verbose_name='total_marks')),
                ('obtained_marks', models.CharField(max_length=30, verbose_name='obtained_marks')),
                ('assesment_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Assesment')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class')),
                ('exam_Gr_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='student_information.Gr')),
                ('exam_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam')),
                ('quater_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Quater')),
                ('semester_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semester')),
                ('semesterbreakup_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semesterbreakup')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='exam_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='quater_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Quater'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='semester_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semester'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='semesterbreakup_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semesterbreakup'),
        ),
    ]
