# Generated by Django 3.0.3 on 2020-03-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
