# Generated by Django 3.0.3 on 2020-03-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0002_auto_20200306_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='exam_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_code',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
