# Generated by Django 3.0.3 on 2020-03-06 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_auto_20200306_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='exam_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
    ]
