# Generated by Django 3.0.3 on 2020-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20200306_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quater',
            name='exam_code',
        ),
        migrations.RemoveField(
            model_name='quater',
            name='semester_code',
        ),
        migrations.RemoveField(
            model_name='quater',
            name='semesterbreakup_code',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='exam_code',
        ),
        migrations.RemoveField(
            model_name='semesterbreakup',
            name='exam_code',
        ),
        migrations.RemoveField(
            model_name='semesterbreakup',
            name='semester_code',
        ),
        migrations.DeleteModel(
            name='Assesment',
        ),
        migrations.DeleteModel(
            name='Quater',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Semesterbreakup',
        ),
    ]
