# Generated by Django 3.0.3 on 2020-03-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0006_assesment_quater_semester_semesterbreakup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='exam_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='quater_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Quater'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='semester_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semester'),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='semesterbreakup_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semesterbreakup'),
        ),
        migrations.AlterField(
            model_name='quater',
            name='exam_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
        migrations.AlterField(
            model_name='quater',
            name='semester_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semester'),
        ),
        migrations.AlterField(
            model_name='quater',
            name='semesterbreakup_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semesterbreakup'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='semesterbreakup',
            name='exam_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
        migrations.AlterField(
            model_name='semesterbreakup',
            name='semester_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Semester'),
        ),
    ]
