# Generated by Django 3.0 on 2020-03-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_information', '0001_initial'),
        ('dependencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveAttendence',
            fields=[
                ('attendence_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('attendence_date', models.DateField()),
                ('attendence_checkBox', models.CharField(max_length=20)),
                ('attendence_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class')),
                ('attendence_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Family')),
                ('attendence_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr')),
                ('attendence_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SelectAttendence',
            fields=[
                ('select_attendence_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('checkBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.SaveAttendence')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Family')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Section')),
            ],
        ),
    ]
