# Generated by Django 3.0.4 on 2020-03-28 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '0001_initial'),
        ('student_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveAttendence',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('attendence', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Family')),
                ('gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Section')),
            ],
        ),
    ]
