# Generated by Django 3.0.3 on 2020-03-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveAttendence',
            fields=[
                ('attendence_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('attendence_date', models.DateField()),
                ('attendence_checkBox', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SelectAttendence',
            fields=[
                ('select_attendence_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('checkBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.SaveAttendence')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Family')),
            ],
        ),
    ]
