# Generated by Django 3.0.3 on 2020-03-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveattendence',
            old_name='father',
            new_name='family',
        ),
    ]
