# Generated by Django 3.0 on 2020-03-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectAttendence',
        ),
    ]
