# Generated by Django 3.0.3 on 2020-03-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_information', '0001_initial'),
        ('attendence', '0001_initial'),
        ('dependencies', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectattendence',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr'),
        ),
        migrations.AddField(
            model_name='selectattendence',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Section'),
        ),
        migrations.AddField(
            model_name='saveattendence',
            name='attendence_classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class'),
        ),
        migrations.AddField(
            model_name='saveattendence',
            name='attendence_father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Family'),
        ),
        migrations.AddField(
            model_name='saveattendence',
            name='attendence_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr'),
        ),
        migrations.AddField(
            model_name='saveattendence',
            name='attendence_sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Section'),
        ),
    ]
