# Generated by Django 3.0 on 2020-03-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0001_initial'),
        ('student_information', '0001_initial'),
        ('attendence', '0002_delete_selectattendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectAttendence',
            fields=[
                ('select_attendence_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('checkBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.SaveAttendence')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Class')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Family')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_information.Gr')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Section')),
            ],
        ),
    ]
