# Generated by Django 3.0.3 on 2020-02-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('surname', models.CharField(max_length=200, unique=True)),
                ('father_name', models.CharField(max_length=200)),
                ('ph_no_father', models.CharField(max_length=11, unique=True)),
                ('mother_name', models.CharField(max_length=200)),
                ('ph_no_mother', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gr',
            fields=[
                ('gr_number', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('query_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.FileField(upload_to='images')),
                ('family_code', models.IntegerField()),
                ('fee_catogery_code', models.IntegerField()),
                ('class_of_admission', models.CharField(max_length=15)),
                ('session_of_admission', models.IntegerField()),
                ('current_class', models.CharField(max_length=15)),
                ('current_session', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('last_school', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=20)),
            ],
        ),
    ]
