# Generated by Django 3.0.3 on 2020-02-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gr',
            fields=[
                ('gr_number', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('query_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.FileField(upload_to='images')),
                ('fee_catogery_code', models.IntegerField()),
                ('class_of_admission', models.CharField(max_length=15)),
                ('session_of_admission', models.IntegerField()),
                ('current_class', models.CharField(max_length=15)),
                ('current_session', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('last_school', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=20)),
                ('family_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Family')),
            ],
            options={
                'verbose_name': 'Gr',
                'verbose_name_plural': 'Grs',
                'ordering': ('name',),
            },
        ),
    ]
